---
title: "plastic"
author: "Jen Richmond"
date: "21/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
```


```{r}


coast_vs_waste <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv") 

mismanaged_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv") 


waste_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-plastic-waste-vs-gdp-per-capita.csv") 
```

```{r}
names(waste_vs_gdp)

waste_vs_gdp <- clean_names(waste_vs_gdp)
```

```{r}
western <- waste_vs_gdp %>% 
  filter(entity %in% c("Austrlia", "New Zealand", "Canada", "United Kingdom", "United States")) %>%
  filter(year > 2000) %>%
  arrange(desc(per_capita_plastic_waste_kilograms_per_person_per_day))
```

```{r}
waste_vs_gdp %>% 
  
  ggplot(aes(x = year, y = per_capita_plastic_waste_kilograms_per_person_per_day, group = entity, colour = entity)) +
  geom_point() +
  geom_line()
```

