---
title: "week3 art"
date: 2021-01-13
output: html_output
---



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(janitor)
library(here)

source(here("other_scripts", "theme_jen.R"))

```

# Load the weekly Data

```{r}
artists <- read_csv(here("data", "w3_artist.csv")
                    
                    works <- read_csv(here("data", "w3_works.csv")
```


Question: has the gender distribution of artists represented at the TATE changed over time?

```{r Wrangle}

artists %>%
  tabyl(gender)

```
Yikes 85% male!

What about over time, earliest artist born 1497

```{r}
artists %>%
  na.omit() %>%
  summarise(minBirth = min(yearOfBirth), minDeath = min(yearOfDeath),
            maxBirth = max(yearOfBirth), maxDeath = max(yearOfDeath))
```

Add new column with century

```{r}

fifteens <- 1500:1599
sixteens <- 1600:1699
seventeens <- 1700:1799
eighteens <- 1800:1899
nineteens <- 1900:1999
twenties <- 2000:2100

   artists_century <- artists %>%
  mutate(centurydeath = case_when(yearOfDeath %in% fifteens ~ "1500s", 
                             yearOfDeath %in% sixteens ~ "1600s",
                             yearOfDeath %in% seventeens ~ "1700s",
                             yearOfDeath %in% eighteens ~ "1800s",
                             yearOfDeath %in% nineteens ~ "1900s",
                             yearOfDeath %in% twenties ~ "2000s",
                             )) %>%
       mutate(centurybirth= case_when(yearOfBirth %in% fifteens ~ "1500s", 
                             yearOfBirth %in% sixteens ~ "1600s",
                             yearOfBirth %in% seventeens ~ "1700s",
                             yearOfBirth %in% eighteens ~ "1800s",
                             yearOfBirth %in% nineteens ~ "1900s",
                             yearOfBirth %in% twenties ~ "2000s",
                             )) 
```

```{r}
artists_century %>%
  na.omit() %>%
  tabyl(centurydeath, gender)

artists_century %>%
  tabyl(centurybirth, gender)
```

# modern artists

filter for those born since 1900

```{r}
modern <- artists %>%
  filter(yearOfBirth > 1900) 

modern %>%
  tabyl(gender)
                            
```

```{r}
zeros <- 1900:1909
teens <- 1910:1919
two <- 1920:1929
three <- 1930:1939
four <- 1940:1949
five <- 1950:1959
six <- 1960:1969
seven <- 1970:1979
eight <- 1980:1989
nine <- 1990:1999
mill <- 2000:2009
mill_teen <- 2010:2019

 modern_decade <- modern %>%
          mutate(decade_birth = case_when(yearOfBirth %in% zeros ~ "00s", 
                             yearOfBirth %in% teens ~ "10s",
                             yearOfBirth %in% two ~ "20s",
                             yearOfBirth %in% three ~ "30s",
                             yearOfBirth %in% four ~ "40s",
                             yearOfBirth %in% five ~ "50s",
                              yearOfBirth %in% six ~ "60s",
                              yearOfBirth %in% seven ~ "70s",
                              yearOfBirth %in% eight ~ "80s",
                              yearOfBirth %in% nine ~ "90s",
                              yearOfBirth %in% mill ~ "2000s",
                              yearOfBirth %in% mill_teen ~ "2010s",
                             ))
 
 modern_decade$decade <- fct_relevel(modern_decade$decade, c("00s", "10s", "20s", "30s", "40s", "50s", "60s", "70s", "80s", "90s", "2000s", "2010s"))

```




```{r Visualize}

modern_decade %>%
  count(decade, gender) %>%
  ggplot(aes(x = decade, y = n, fill = gender)) +
  geom_col() +
  labs(x = "Decade of Artist birth", y = "Number of artists", title = "Artists born since 1900, gender distribution") +
  theme_jen()
  
```




# Save Image

Save your image for sharing. Be sure to use the `#TidyTuesday` hashtag in your post on twitter! 

```{r}

# This will save your most recent plot
ggsave(
  filename = "My TidyTuesday Plot.png",
  device = "png")

```
