---
title: "tvratings"
author: "Jen Richmond"
date: "06/01/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#### load packages
```{r}
library(tidyverse)
library(lubridate)
```

#### read in ratings data from github

```{r}
ratings <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-08/IMDb_Economist_tv_ratings.csv") 
```

#### clean it up a bit

- separate genres column into several
- format date column 
- make new column  with just year
- make year factor (rather than numeric)  

```{r}
ratings <- ratings %>%
 separate(genres, c("genre1", "genre2", "genre3", "genre4"), remove = FALSE) %>%
  mutate(date = as.Date(date, format = "%y/%m/%dd")) %>%
   mutate(year = year(date)) %>%
  mutate(year = as.factor(year))
```

#### check clean up with glimpse

```{r}
glimpse(ratings)
```

#### plotting average ratings by date 

Looks like lots more shows since 2010

```{r}
ratings %>%
  ggplot(aes(x = date, y= av_rating)) +
  geom_line() 
```

#### plot show count by year



```{r}
ratings %>%
  group_by(year) %>%
  summarise(count = n()) %>%
  ggplot(aes(x= year, y= count)) +
  geom_col() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Number of shows produced each year", y = "Number of shows", x = "Year")

ggsave("showsperyear.png")
```


#### plot show count by genre and year

```{r}
ratings %>%
  group_by(year, genre1) %>%
  summarise(count = n()) %>%
  filter(genre1 != "Documentary") %>%
  ggplot(aes(x= year, y= count, color = genre1, group = genre1)) +
  geom_point() +
  geom_line() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_color_discrete(name = "Genre", breaks=c("Drama","Crime","Action","Comedy", "Adventure", "Animation", "Biography", "Documentary")) +
  labs(title = "Number of shows produced each year by genre", subtitle = "(first genre listed)", y = "Number of shows", x = "Year")

ggsave("showsperyearbygenre.png")

```

